### ISSUE TITLE
nrepl under macOS not working

### ISSUE THREAD

**Issue by kwccoin** [littleredcomputer/sicmutils#34]
Just read your posting in hacking news and trying.  

So far the uberjar work except the release no. is now 0.12

"java -jar target/uberjar/sicmutils-0.12.0-SNAPSHOT-standalone.jar  < demo.clj"

and test ok:

`
2019-04-28 11:18:21.648 WARNING sicmutils.polynomial-factor Assuming (non-negative? I) in root-out-squares

lein test sicmutils.sicm.ch6-test

lein test sicmutils.sicm.ch7-test

lein test sicmutils.simplify-test

lein test sicmutils.structure-test

lein test sicmutils.tex-web-test

lein test sicmutils.value-test

Ran 186 tests containing 1815 assertions.
0 failures, 0 errors.

`  

But not the nrepl even after I add the dependence of [nrepl "0.6.0"] there.  Not sure how to resolve this.

`
lein repl < demo.clj
[WARNING] No nREPL middleware descriptor in metadata of #'sicmutils.repl/math-printer, see nrepl.middleware/set-descriptor!
nREPL server started on port 58542 on host 127.0.0.1 - nrepl://127.0.0.1:58542
ERROR: Unhandled REPL handler exception processing message {:id c6311d23-bcc6-4f15-81ff-400678d0f83a, :op clone}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: sicmutils.repl$math_printer$fn$reify__10495
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at nrepl.transport$eval9398$fn__9399$G__9389__9406.invoke(transport.clj:16)
	at nrepl.middleware.print$send_nonstreamed.invokeStatic(print.clj:157)
	at nrepl.middleware.print$send_nonstreamed.invoke(print.clj:138)
	at nrepl.middleware.print$printing_transport$reify__9891.send(print.clj:174)
	at nrepl.middleware.caught$caught_transport$reify__9926.send(caught.clj:58)
	at nrepl.middleware.session$register_session.invokeStatic(session.clj:205)
	at nrepl.middleware.session$register_session.invoke(session.clj:197)
	at nrepl.middleware.session$session$fn__10123.invoke(session.clj:267)
	at nrepl.middleware$wrap_conj_descriptor$fn__9678.invoke(middleware.clj:16)
	at nrepl.middleware.caught$wrap_caught$fn__9935.invoke(caught.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__9678.invoke(middleware.clj:16)
	at nrepl.middleware.print$wrap_print$fn__9902.invoke(print.clj:234)
	at nrepl.middleware$wrap_conj_descriptor$fn__9678.invoke(middleware.clj:16)
	at sicmutils.repl$math_printer$fn__10493.invoke(repl.clj:39)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__1107.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__10160.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

I add this to the project.cly btw,

`
  -               [potemkin "0.4.3"]]
  +               [potemkin "0.4.3"]
  +           	 [nrepl "0.6.0"]]
`

Just in case I do a "lein new app testapp" and it does launch the nrepl and hence may be even the additional dependence is not needed.

'
lein repl
nREPL server started on port 59408 on host 127.0.0.1 - nrepl://127.0.0.1:59408
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

testapp.core=> (+ 1 2)
3
testapp.core=> Bye for now!

'

There must be something in the code that trigger the error message.

**Comment by littleredcomputer** [comment]
thanks! I will take a look.

**Comment by littleredcomputer** [comment]
I appreciate the report. I've taken the opportunity to simplify a few things around repl handling and pushed a new snapshot. Please give it another try.
